export const FETCH_FOOTER_SUCCESS = "FETCH_FOOTER_SUCCESS";
export const FETCH_FOOTER_FAILURE = "FETCH_FOOTER_FAILURE";
export const FETCH_FOOTER = "FETCH_FOOTER";
export const FETCH_NAVBAR_SUCCESS = "FETCH_NAVBAR_SUCCESS";
export const FETCH_NAVBAR_FAILURE = "FETCH_NAVBAR_FAILURE";
export const FETCH_NAVBAR = "FETCH_NAVBAR";
